HotelMenagmentClientNew/Models/ErrorViewModel.cs
using System;

namespace HotelMenagmentClientNew.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

HotelMenagmentClientNew/Models/GuestDTO.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HotelMenagmentClientNew.Models
{
    public class GuestDTO
    {
        public int GuestID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public DateTimeOffset Member_since { get; set; }
    }
}

HotelMenagmentClientNew/Models/HotelViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HotelMenagmentClientNew.Models
{
    public class HotelViewModel
    {
        public ICollection<RoomDTO> RoomList { get; set; }
        public ICollection<GuestDTO> GuestList { get; set; }
        public ICollection<ReservationDTO> ReservationList { get; set; }
        public List<ReservationHistoryDTO> ReservationHistoryList { get; set; }
        public List<ReservationDTO> ReservedForToday { get; set; }
    }
}

HotelMenagmentClientNew/Models/ReservationDTO.cs
using HotelMenagmentClientNew.Services;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace HotelMenagmentClientNew.Models
{
    public class ReservationDTO
    {
        public int ReservationID { get; set; }

        [Display(Name = "Checkin Date")]
        [DataType(DataType.Date)]

        public DateTimeOffset Check_in { get; set; }

        [Display(Name = "Checkout Date")]
        [DataType(DataType.Date)]

        public DateTimeOffset Check_out { get; set; }
        public ResStatus Status { get; set; }
        public string Made_by { get; set; }
        //public int GuestID { get; set; }
        public Guest Guest { get; set; }

        public string GuestName { get; set; }
        //public int RoomID { get; set; }
        public Room Room { get; set; }
    }
}

HotelMenagmentClientNew/Models/ReservationHistoryDTO.cs
using HotelMenagmentClientNew.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HotelMenagmentClientNew.Models
{
    public class ReservationHistoryDTO
    {
        public int ReservationHistoryID { get; set; }
        public DateTimeOffset Check_in_History { get; set; }
        public DateTimeOffset Check_out_History { get; set; }
        //public int GuestID_History { get; set; }
        public Guest Guest { get; set; }
        public string GuestName_History { get; set; }
        //public int RoomID_History { get; set; }
        public Room Room { get; set; }
    }
}

HotelMenagmentClientNew/Models/RoomDTO.cs
using HotelMenagmentClientNew.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HotelMenagmentClientNew.Models
{
    public class RoomDTO
    {
        public int RoomID { get; set; }
        public int Number { get; set; }
        public string Name { get; set; }
        public bool Is_ocuppied { get; set; }
        public bool Smoke { get; set; }
        public RoomType Nubmerbeds { get; set; }
        //public string Guest { get; set; }
    }
}

HotelMenagmentClientNew/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using HotelMenagmentClientNew.Models;

namespace HotelMenagmentClientNew.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

HotelMenagmentClientNew/Controllers/ReservationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HotelMenagmentClientNew.Models;
using HotelMenagmentClientNew.Services;
using Microsoft.AspNetCore.Mvc;

namespace HotelMenagmentClientNew.Controllers
{
    public class ReservationController : Controller
    {
        private readonly ReservationService _reservationService;

        public ReservationController(ReservationService reservationService)
        {
            _reservationService = reservationService;
        }

        public async Task <IActionResult> Index()
        {
            ICollection<ReservationDTO> reservationToDisplay = await _reservationService.GetAllReservations();
            var model = new HotelViewModel()
            {
                ReservationList = reservationToDisplay
            };
            return View(model);
        }
    }
}

HotelMenagmentClientNew/Controllers/RoomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HotelMenagmentClientNew.Models;
using HotelMenagmentClientNew.Services;
using Microsoft.AspNetCore.Mvc;

namespace HotelMenagmentClientNew.Controllers
{
    public class RoomController : Controller
    {
        private readonly RoomService _roomService;

        public RoomController(RoomService roomService)
        {
            _roomService = roomService;
        }

        public async Task<IActionResult> Index()
        {
            ICollection<RoomDTO> roomsToDisplay = await _roomService.GetAllRooms();

            var model = new HotelViewModel()
            {
                RoomList = roomsToDisplay
            };
            return View(model);
        }
    }
}

HotelMenagmentClientNew/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HotelMenagmentClientNew.Models;
using HotelMenagmentClientNew.Services;
using Microsoft.AspNetCore.Mvc;

namespace HotelMenagmentClientNew.Controllers
{
    public class UserController : Controller
    {
        private readonly UserService _userService;

        public UserController(UserService userService)
        {
            _userService = userService;
        }

        public async Task<IActionResult> Index()
        {
            ICollection<GuestDTO> guestsToDisplay = await _userService.GetAll();

            var model = new HotelViewModel()
            {
                GuestList = guestsToDisplay
            };
            /*var guests = from n in _userService.GetAll()
                              select n;
            var guestVM = new HotelViewModel
            {
                GuestList = singleguest.ToList()
            };
            return View(guestVM);*/
            return View(model);
        }
    }
}

HotelMenagmentClientNew/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

HotelMenagmentClientNew/Views/Reservation/Index.cshtml
@model HotelViewModel;
@{
    ViewData["Title"] = "Reservation List";
}
<p>Reservations</p>
<div class="container">
    <table class="table table-hover">
        <thead>
            <tr>

                <td>ReservationId</td>
               
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.ReservationList)
            {
                <tr>

                    <td>@item.ReservationID</td>
                   
                </tr>
            }
        </tbody>
    </table>
</div>

HotelMenagmentClientNew/Views/Room/Index.cshtml
@model HotelViewModel;
@{
    ViewData["Title"] = "Room List";
}
<h2>Rooms</h2>

<div class="container">
    <table class="table table-hover">
        <thead>
            <tr>

                <td>RoomId</td>
                <td>Name</td>
                <td>IsOccupies</td>
                <td>For Smokers</td>
                <td>Room Type</td>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.RoomList)
            {
                <tr>

                    <td>@item.RoomID</td>
                    <td>@item.Name</td>
                    <td>@item.Is_ocuppied</td>
                    <td>@item.Smoke</td>
                    @if(item.Nubmerbeds.ToString()== "2") 
                    { 
                    <td>double</td>
                    }
                    @if (item.Nubmerbeds.ToString() == "_1")
                    {
                    <td>single</td>                        
                    }
                </tr>
            }
        </tbody>
    </table>
</div>

HotelMenagmentClientNew/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HotelMenagmentClientNew</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HotelMenagmentClientNew</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Room" asp-action="Index">Rooms</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Reservation" asp-action="Index">Reservation</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - HotelMenagmentClientNew - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

HotelMenagmentClientNew/Views/User/Index.cshtml
@model HotelViewModel;
@{
    ViewData["Title"] = "User List";
}

<h2>Users</h2>

<div class="container">
    <table class="table table-hover">
        <thead>
            <tr>

                <td>GuestId</td>
                <td>Name</td>
                <td>Suraname</td>
                <td>Client since</td>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.GuestList)
            {
                <tr>

                    <td>@item.GuestID</td>
                    <td>@item.Name</td>
                    <td>@item.Surname</td>
                    <td>@item.Member_since.Year</td>
                </tr>
            }
        </tbody>
    </table>
</div>